var questions = [
    { question: "1. How many types of stem cells are there?", 
      answer: "<br>1) <b>Totipotent (or Omnipotent) Stem Cells</b>: These are the most potent stem cells, capable of differentiating into any of the 220 cell types found in an embryo as well as extra-embryonic cells (like the placenta). An example of totipotent cells is the zygote, the fertilized egg. <br>2) <b>Pluripotent Stem Cells</b>: These stem cells can give rise to all cell types of the body (but not the placenta). Examples of pluripotent stem cells include embryonic stem (ES) cells and induced pluripotent stem (iPS) cells.<br>3) <b>Multipotent Stem Cells</b>: These stem cells can develop into a limited number of cell types in a particular lineage1. An example of multipotent stem cells is hematopoietic stem (HS) cells, which can differentiate into various types of blood cells. <br>4) <b>Oligopotent Stem Cells</b>: These stem cells can differentiate into a few closely related cell types5. An example would be lymphoid or myeloid stem cells, which are believed to originate from HSCs, in the bone marrow. <br>5) <b>Unipotent Stem Cells</b>: These stem cells can produce only one cell type, their own, but have the property of self-renewal, which distinguishes them from non-stem cells5. An example would be muscle stem cells.", 
      frequency: 1, 
      tags: ["basic","cellbio"], 
      imageUrl: "imageassets/1.png", 
      occasion: "HCZ QE: Suspension Culture & AKTi4 as Antibacterials", 
      asker: "Prof. Tzu-Ming LIU" },
    
    { question: "2. Could adherence and morphology affect ESC differentiation?", 
      answer: "<br>1. Research conducted by Dr. DCH and ZZY demonstrated that cells located near the edges of the ES colonies are more sensitive to induction. <br>2. Some biomaterial research pointed out mechanics could be used to regulate stem cell differentiation.", 
      frequency: 1, 
      tags: ["cellbio"], 
      imageUrl:"imageassets/2.jpg", 
      occasion: "HCZ QE: Suspension Culture & AKTi4 as Antibacterials", 
      asker: "Prof. WANG Chunming" },
    
    { question: "3. Which organisms do not have mesoderm.", 
      answer: "<br>Diploblastic organisms, such as jellyfishes, coral, sea-pens, etc. ", 
      frequency: 1, 
      tags: ["basic","devbio"], 
      occasion: "ZZY QE"},

    { question: "4. What are the advantages and disadvantages of a differentiation method?", 
      answer: "<br> These are some aspects to consider.<br><b>Efficiency</b>: How many of the hESCs are successfully differentiated into the desired cell type?<br><b>Purity</b>: Are the differentiated cells pure, or are there other cell types present?<br><b>Time</b>: How long does the differentiation process take?<br><b>Cost</b>: What are the costs associated with the differentiation method? This includes the cost of reagents, equipment, and labour.<br><b>Reproducibility</b>: Can the differentiation method be reliably reproduced, both within the same lab and in other labs?<br><b>Ethical considerations</b>: Are there any ethical issues associated with the method?",
      frequency: 1,
      tags: ["basic"], 
      occasion: "FSC QE: Keratinocyte Differentiation",
      asker: "Prof. WANG Chunming"},

    { question: "5. What are the lineages that could be induced along the embryonic and extraembryonic differentiation?", 
      answer: "<br><b>Endoderm</b>: Visceral tissues and organs such as lungs, livers, intestines, etc.<br><b>Mesoderm</b>: Bones, muscles, and cardiac tissues.<br><b>Ectoderm</b>: Skin and neural system.<br><b>Extraembryonic</b>: trophoblast, which further develops into placenta, extraembryonic endoderm, which further develops into yolk sac's lining, and extraembryonic mesoderm, which further develops into yolk sac, chorion, and allantois.", 
      frequency: 1, 
      tags: ["basic","devcell"], 
      occasion: "FSC QE: Keratinocyte Differentiation",
      asker: "Prof. XU Ren-he"},

    { question: "6. What are the potential hurdles for cell therapy?", 
      answer: "<br> These are some aspects to consider.<br> Immunogenicity, cell survival, tumorigenicity (teratoma for remaining PSCs, fibroma and neoplasia for MSCs), limitations in the form of cell preparations/administrations, and regulatory requirements.", 
      frequency: 1, 
      tags: ["tech"], 
      occasion: "FSC QE: Keratinocyte Differentiation",
      asker: "Prof. XU Ren-he"},

    { question: "7. Could 3D culture help the differentiation?", 
      answer: "<br> These are generally two forms of 3D cell culture, suspension and matrix-based.<br> Suspension culture is helpful to expand the cells and with the help of regulatory molecules endogenously secreted or from adjacent cells, differentiation into certain cell types or organoids is feasible.<br> Matrix-based 3D cell culture aims to provide ECM for cells and helps the administration of cells as patches or injectable preparations. Sometimes, mechanics or modification with regulatory molecules could regulate the differentiation.", 
      frequency: 1, 
      tags: ["tech"], 
      occasion: "FSC QE: Keratinocyte Differentiation",
      asker: "Prof. XU Ren-he"},

    { question: "8. What cell fate could be induced by BMP4?", 
      answer: "<br><b>1. Trophoblasts</b><br><b>2. Mesodermal cells</b><br><b>3. Endodermal cells (w/ Activin A)</b><br><b>4. Amniotic cells</b><br>The final differentiated types of cells depend on the timing and dosage.", 
      frequency: 1, 
      tags: ["tech"], 
      occasion: "FSC QE: Keratinocyte Differentiation",
      asker: "Prof. XU Ren-he"}, 
    // Add more questions here...
];
